---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  CART_ENDPOINT: "cart"
  DB_HOST: "mysql"
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    name: shipping
    tier: backend
spec:
  containers:
  - name: shipping
    imagePullPolicy: Always
    image: dockerswaha/shipping:k8
    envFrom:
    - configMapRef:
        name: shipping-config
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    name: shipping
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080