apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
    tier: db
spec:
  containers:
  - name: rabbitmq
    imagePullPolicy: Always
    image: rabbitmq
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
    - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    name: rabbitmq
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672